name: All Tests

on: [push, pull_request]

jobs:
    build:
      name: Check
      runs-on: ubuntu-latest
      env:
        GO111MODULE: on

      steps:

        - name: Check out code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: "1.24"

        - name: Install libraries
          run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends bash-completion libnuma1 libncurses6
            sudo apt-get install -y --no-install-recommends libaio1t64 || sudo apt-get install -y --no-install-recommends libaio1

        - name: tests
          run: ./scripts/ci.sh
